CREATE TABLE IF NOT EXISTS "breach_chains" (
	"id" varchar PRIMARY KEY NOT NULL,
	"organization_id" varchar DEFAULT 'default' NOT NULL,
	"name" varchar NOT NULL,
	"description" text,
	"asset_ids" jsonb NOT NULL,
	"target_domains" jsonb,
	"config" jsonb NOT NULL,
	"status" varchar DEFAULT 'pending' NOT NULL,
	"current_phase" varchar,
	"progress" integer DEFAULT 0 NOT NULL,
	"phase_results" jsonb DEFAULT '[]'::jsonb,
	"current_context" jsonb,
	"unified_attack_graph" jsonb,
	"overall_risk_score" integer,
	"total_credentials_harvested" integer,
	"total_assets_compromised" integer,
	"domains_breached" jsonb,
	"max_privilege_achieved" varchar,
	"executive_summary" text,
	"started_at" timestamp,
	"completed_at" timestamp,
	"duration_ms" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
