export interface ComplianceControl {
  id: string;
  family: string;
  title: string;
  description: string;
  priority: "P1" | "P2" | "P3";
  securityFunction?: string;
}

export interface ComplianceFramework {
  id: string;
  name: string;
  version: string;
  description: string;
  controls: ComplianceControl[];
}

export const NIST_800_53_CONTROLS: ComplianceControl[] = [
  { id: "AC-1", family: "Access Control", title: "Policy and Procedures", description: "Develop and maintain access control policies and procedures", priority: "P1" },
  { id: "AC-2", family: "Access Control", title: "Account Management", description: "Manage system accounts including establishing, activating, modifying, reviewing, disabling, and removing accounts", priority: "P1" },
  { id: "AC-3", family: "Access Control", title: "Access Enforcement", description: "Enforce approved authorizations for logical access to information and system resources", priority: "P1" },
  { id: "AC-4", family: "Access Control", title: "Information Flow Enforcement", description: "Enforce approved authorizations for controlling the flow of information within the system", priority: "P1" },
  { id: "AC-5", family: "Access Control", title: "Separation of Duties", description: "Separate duties of individuals to prevent malicious activity", priority: "P1" },
  { id: "AC-6", family: "Access Control", title: "Least Privilege", description: "Employ the principle of least privilege, allowing only authorized accesses", priority: "P1" },
  { id: "AC-7", family: "Access Control", title: "Unsuccessful Logon Attempts", description: "Enforce limits on consecutive invalid logon attempts", priority: "P1" },
  { id: "AC-17", family: "Access Control", title: "Remote Access", description: "Establish and document usage restrictions for remote access connections", priority: "P1" },
  { id: "AU-1", family: "Audit and Accountability", title: "Policy and Procedures", description: "Develop and maintain audit and accountability policies", priority: "P1" },
  { id: "AU-2", family: "Audit and Accountability", title: "Event Logging", description: "Identify events that the system is capable of logging", priority: "P1" },
  { id: "AU-3", family: "Audit and Accountability", title: "Content of Audit Records", description: "Audit records must contain sufficient information to establish context", priority: "P1" },
  { id: "AU-6", family: "Audit and Accountability", title: "Audit Record Review", description: "Review and analyze audit records for indications of inappropriate activity", priority: "P1" },
  { id: "AU-12", family: "Audit and Accountability", title: "Audit Record Generation", description: "Generate audit records for events identified by the organization", priority: "P1" },
  { id: "CA-2", family: "Assessment, Authorization, and Monitoring", title: "Control Assessments", description: "Assess security controls to determine effectiveness", priority: "P2" },
  { id: "CA-7", family: "Assessment, Authorization, and Monitoring", title: "Continuous Monitoring", description: "Develop and implement continuous monitoring strategy", priority: "P1" },
  { id: "CM-2", family: "Configuration Management", title: "Baseline Configuration", description: "Develop and maintain baseline configurations for systems", priority: "P1" },
  { id: "CM-6", family: "Configuration Management", title: "Configuration Settings", description: "Establish and document security configuration settings", priority: "P1" },
  { id: "CM-7", family: "Configuration Management", title: "Least Functionality", description: "Configure systems to provide only essential capabilities", priority: "P1" },
  { id: "IA-2", family: "Identification and Authentication", title: "Identification and Authentication", description: "Uniquely identify and authenticate organizational users", priority: "P1" },
  { id: "IA-5", family: "Identification and Authentication", title: "Authenticator Management", description: "Manage system authenticators by establishing controls", priority: "P1" },
  { id: "IR-4", family: "Incident Response", title: "Incident Handling", description: "Implement incident handling capability for security incidents", priority: "P1" },
  { id: "IR-6", family: "Incident Response", title: "Incident Reporting", description: "Report incidents to designated authorities within defined time frames", priority: "P1" },
  { id: "RA-3", family: "Risk Assessment", title: "Risk Assessment", description: "Conduct periodic assessments of organizational operations risk", priority: "P1" },
  { id: "RA-5", family: "Risk Assessment", title: "Vulnerability Monitoring and Scanning", description: "Scan for vulnerabilities and update vulnerability databases", priority: "P1" },
  { id: "SA-11", family: "System and Services Acquisition", title: "Developer Testing and Evaluation", description: "Require the developer to create and implement security assessment plan", priority: "P2" },
  { id: "SC-7", family: "System and Communications Protection", title: "Boundary Protection", description: "Monitor and control communications at the external system boundary", priority: "P1" },
  { id: "SC-8", family: "System and Communications Protection", title: "Transmission Confidentiality", description: "Protect the confidentiality of transmitted information", priority: "P1" },
  { id: "SC-13", family: "System and Communications Protection", title: "Cryptographic Protection", description: "Implement cryptographic mechanisms to prevent unauthorized disclosure", priority: "P1" },
  { id: "SI-2", family: "System and Information Integrity", title: "Flaw Remediation", description: "Identify, report, and correct system flaws in a timely manner", priority: "P1" },
  { id: "SI-3", family: "System and Information Integrity", title: "Malicious Code Protection", description: "Implement malicious code protection mechanisms", priority: "P1" },
  { id: "SI-4", family: "System and Information Integrity", title: "System Monitoring", description: "Monitor the system to detect attacks and unauthorized connections", priority: "P1" },
];

export const PCI_DSS_REQUIREMENTS: ComplianceControl[] = [
  { id: "1.1", family: "Network Security", title: "Network Security Controls", description: "Install and maintain network security controls", priority: "P1" },
  { id: "1.2", family: "Network Security", title: "Network Segmentation", description: "Restrict connections between untrusted networks and CDE", priority: "P1" },
  { id: "2.1", family: "Secure Configurations", title: "Change Defaults", description: "Change vendor-supplied defaults before installing on the network", priority: "P1" },
  { id: "2.2", family: "Secure Configurations", title: "System Hardening", description: "Develop configuration standards for all system components", priority: "P1" },
  { id: "3.1", family: "Account Data Protection", title: "Data Retention", description: "Keep cardholder data storage to a minimum", priority: "P1" },
  { id: "3.4", family: "Account Data Protection", title: "PAN Protection", description: "Render PAN unreadable anywhere it is stored", priority: "P1" },
  { id: "3.5", family: "Account Data Protection", title: "Cryptographic Key Protection", description: "Secure cryptographic keys used to protect stored account data", priority: "P1" },
  { id: "4.1", family: "Transmission Encryption", title: "Strong Cryptography", description: "Use strong cryptography to protect cardholder data during transmission", priority: "P1" },
  { id: "5.1", family: "Malware Protection", title: "Anti-Malware", description: "Deploy anti-malware solution on all systems commonly affected by malware", priority: "P1" },
  { id: "5.2", family: "Malware Protection", title: "Malware Prevention", description: "Prevent, detect, and address malware", priority: "P1" },
  { id: "6.1", family: "Secure Development", title: "Security Vulnerabilities", description: "Identify security vulnerabilities using reputable sources", priority: "P1" },
  { id: "6.2", family: "Secure Development", title: "Security Patches", description: "Install applicable security patches to protect all system components", priority: "P1" },
  { id: "6.3", family: "Secure Development", title: "Secure Development Practices", description: "Develop software applications securely", priority: "P1" },
  { id: "6.4", family: "Secure Development", title: "Change Control", description: "Follow change control processes for all changes to system components", priority: "P1" },
  { id: "7.1", family: "Access Control", title: "Access Restriction", description: "Limit access to system components to only those whose job requires access", priority: "P1" },
  { id: "7.2", family: "Access Control", title: "Access Control Systems", description: "Establish an access control model based on job classification and function", priority: "P1" },
  { id: "8.1", family: "Identification and Authentication", title: "User Identification", description: "Assign a unique ID to each person with computer access", priority: "P1" },
  { id: "8.2", family: "Identification and Authentication", title: "Strong Authentication", description: "Employ at least one form of authentication", priority: "P1" },
  { id: "8.3", family: "Identification and Authentication", title: "MFA", description: "Secure all individual administrative access with multi-factor authentication", priority: "P1" },
  { id: "9.1", family: "Physical Access", title: "Physical Access Controls", description: "Use appropriate facility entry controls to limit physical access", priority: "P1" },
  { id: "10.1", family: "Logging and Monitoring", title: "Audit Trails", description: "Implement audit trails to link all access to system components to each user", priority: "P1" },
  { id: "10.2", family: "Logging and Monitoring", title: "Event Logging", description: "Implement automated audit trails for all system components", priority: "P1" },
  { id: "10.4", family: "Logging and Monitoring", title: "Time Synchronization", description: "Use time-synchronization technology to synchronize all critical system clocks", priority: "P1" },
  { id: "10.5", family: "Logging and Monitoring", title: "Audit Trail Security", description: "Secure audit trails so they cannot be altered", priority: "P1" },
  { id: "11.1", family: "Security Testing", title: "Wireless Testing", description: "Test for the presence of wireless access points quarterly", priority: "P1" },
  { id: "11.2", family: "Security Testing", title: "Vulnerability Scans", description: "Run internal and external network vulnerability scans quarterly", priority: "P1" },
  { id: "11.3", family: "Security Testing", title: "Penetration Testing", description: "Perform external and internal penetration testing at least annually", priority: "P1" },
  { id: "12.1", family: "Policies and Procedures", title: "Security Policy", description: "Establish, publish, maintain, and disseminate a security policy", priority: "P1" },
  { id: "12.6", family: "Policies and Procedures", title: "Security Awareness", description: "Implement a formal security awareness program for all personnel", priority: "P1" },
  { id: "12.10", family: "Policies and Procedures", title: "Incident Response", description: "Implement an incident response plan", priority: "P1" },
];

export const SOC2_CRITERIA: ComplianceControl[] = [
  { id: "CC1.1", family: "Control Environment", title: "COSO Principles", description: "Organization demonstrates commitment to integrity and ethical values", priority: "P1" },
  { id: "CC1.2", family: "Control Environment", title: "Board Oversight", description: "Board of directors demonstrates independence and exercises oversight", priority: "P1" },
  { id: "CC1.3", family: "Control Environment", title: "Organizational Structure", description: "Management establishes structures, reporting lines, and responsibilities", priority: "P1" },
  { id: "CC2.1", family: "Communication and Information", title: "Information Quality", description: "Organization obtains or generates relevant, quality information", priority: "P1" },
  { id: "CC2.2", family: "Communication and Information", title: "Internal Communication", description: "Organization internally communicates information necessary to function", priority: "P1" },
  { id: "CC3.1", family: "Risk Assessment", title: "Risk Identification", description: "Organization identifies and assesses risks to objectives", priority: "P1" },
  { id: "CC3.2", family: "Risk Assessment", title: "Fraud Risk", description: "Organization considers potential for fraud in assessing risks", priority: "P1" },
  { id: "CC4.1", family: "Monitoring Activities", title: "Monitoring Controls", description: "Organization selects, develops, and performs ongoing and/or separate evaluations", priority: "P1" },
  { id: "CC4.2", family: "Monitoring Activities", title: "Deficiency Communication", description: "Organization evaluates and communicates internal control deficiencies", priority: "P1" },
  { id: "CC5.1", family: "Control Activities", title: "Control Selection", description: "Organization selects and develops control activities that mitigate risks", priority: "P1" },
  { id: "CC5.2", family: "Control Activities", title: "Technology Controls", description: "Organization selects and develops general control activities over technology", priority: "P1" },
  { id: "CC5.3", family: "Control Activities", title: "Policy Deployment", description: "Organization deploys control activities through policies and procedures", priority: "P1" },
  { id: "CC6.1", family: "Logical and Physical Access", title: "Access Security", description: "Organization implements logical access security software and infrastructure", priority: "P1" },
  { id: "CC6.2", family: "Logical and Physical Access", title: "Access Registration", description: "Prior to issuing credentials, organization registers and authorizes new users", priority: "P1" },
  { id: "CC6.3", family: "Logical and Physical Access", title: "Access Removal", description: "Organization removes access that is no longer required", priority: "P1" },
  { id: "CC6.6", family: "Logical and Physical Access", title: "External Access", description: "Organization implements controls to prevent or detect and act on threat vectors", priority: "P1" },
  { id: "CC6.7", family: "Logical and Physical Access", title: "Information Transmission", description: "Organization restricts transmission of sensitive information to authorized channels", priority: "P1" },
  { id: "CC7.1", family: "System Operations", title: "Change Detection", description: "Organization uses detection and monitoring procedures to identify changes", priority: "P1" },
  { id: "CC7.2", family: "System Operations", title: "Security Monitoring", description: "Organization monitors system components for indications of compromise", priority: "P1" },
  { id: "CC7.3", family: "System Operations", title: "Event Analysis", description: "Organization evaluates security events to determine impact", priority: "P1" },
  { id: "CC7.4", family: "System Operations", title: "Incident Response", description: "Organization responds to identified security incidents", priority: "P1" },
  { id: "CC7.5", family: "System Operations", title: "Incident Recovery", description: "Organization identifies, develops, and implements recovery activities", priority: "P1" },
  { id: "CC8.1", family: "Change Management", title: "Change Authorization", description: "Organization authorizes, documents, and tracks changes to infrastructure", priority: "P1" },
  { id: "CC9.1", family: "Risk Mitigation", title: "Risk Mitigation", description: "Organization identifies, selects, and develops risk mitigation activities", priority: "P1" },
  { id: "CC9.2", family: "Risk Mitigation", title: "Vendor Management", description: "Organization assesses and manages risks associated with vendors", priority: "P1" },
  { id: "A1.1", family: "Availability", title: "Capacity Planning", description: "Organization maintains, monitors, and evaluates current processing capacity", priority: "P1", securityFunction: "Availability" },
  { id: "A1.2", family: "Availability", title: "Environmental Protections", description: "Organization authorizes, designs, and monitors environmental protections", priority: "P1", securityFunction: "Availability" },
  { id: "C1.1", family: "Confidentiality", title: "Confidential Information", description: "Organization identifies and maintains confidential information", priority: "P1", securityFunction: "Confidentiality" },
  { id: "C1.2", family: "Confidentiality", title: "Information Disposal", description: "Organization disposes of confidential information appropriately", priority: "P1", securityFunction: "Confidentiality" },
  { id: "PI1.1", family: "Processing Integrity", title: "Processing Accuracy", description: "Organization uses quality information processing objectives", priority: "P1", securityFunction: "Processing Integrity" },
];

export const HIPAA_CONTROLS: ComplianceControl[] = [
  { id: "164.308(a)(1)", family: "Administrative Safeguards", title: "Security Management Process", description: "Implement policies and procedures to prevent, detect, and correct security violations", priority: "P1" },
  { id: "164.308(a)(2)", family: "Administrative Safeguards", title: "Assigned Security Responsibility", description: "Identify the security official responsible for developing and implementing security policies", priority: "P1" },
  { id: "164.308(a)(3)", family: "Administrative Safeguards", title: "Workforce Security", description: "Implement policies to ensure workforce members have appropriate access to ePHI", priority: "P1" },
  { id: "164.308(a)(4)", family: "Administrative Safeguards", title: "Information Access Management", description: "Implement policies for authorizing access to ePHI", priority: "P1" },
  { id: "164.308(a)(5)", family: "Administrative Safeguards", title: "Security Awareness and Training", description: "Implement a security awareness and training program for all workforce members", priority: "P1" },
  { id: "164.308(a)(6)", family: "Administrative Safeguards", title: "Security Incident Procedures", description: "Implement policies to address security incidents", priority: "P1" },
  { id: "164.308(a)(7)", family: "Administrative Safeguards", title: "Contingency Plan", description: "Establish policies for responding to emergency or disaster", priority: "P1" },
  { id: "164.308(a)(8)", family: "Administrative Safeguards", title: "Evaluation", description: "Perform periodic technical and non-technical evaluation", priority: "P1" },
  { id: "164.310(a)(1)", family: "Physical Safeguards", title: "Facility Access Controls", description: "Implement policies to limit physical access to electronic information systems", priority: "P1" },
  { id: "164.310(a)(2)", family: "Physical Safeguards", title: "Workstation Use", description: "Implement policies that specify proper functions and manner of use for workstations", priority: "P1" },
  { id: "164.310(c)", family: "Physical Safeguards", title: "Workstation Security", description: "Implement physical safeguards for workstations that access ePHI", priority: "P1" },
  { id: "164.310(d)(1)", family: "Physical Safeguards", title: "Device and Media Controls", description: "Implement policies governing receipt and removal of hardware and electronic media", priority: "P1" },
  { id: "164.312(a)(1)", family: "Technical Safeguards", title: "Access Control", description: "Implement technical policies to allow access only to authorized persons", priority: "P1" },
  { id: "164.312(a)(2)(i)", family: "Technical Safeguards", title: "Unique User Identification", description: "Assign a unique name and/or number for identifying and tracking user identity", priority: "P1" },
  { id: "164.312(a)(2)(iii)", family: "Technical Safeguards", title: "Automatic Logoff", description: "Implement procedures that terminate sessions after a period of inactivity", priority: "P1" },
  { id: "164.312(a)(2)(iv)", family: "Technical Safeguards", title: "Encryption and Decryption", description: "Implement mechanism to encrypt and decrypt ePHI", priority: "P1" },
  { id: "164.312(b)", family: "Technical Safeguards", title: "Audit Controls", description: "Implement mechanisms that record and examine activity in systems containing ePHI", priority: "P1" },
  { id: "164.312(c)(1)", family: "Technical Safeguards", title: "Integrity", description: "Implement policies to protect ePHI from improper alteration or destruction", priority: "P1" },
  { id: "164.312(d)", family: "Technical Safeguards", title: "Person or Entity Authentication", description: "Implement procedures to verify that a person or entity seeking access is the one claimed", priority: "P1" },
  { id: "164.312(e)(1)", family: "Technical Safeguards", title: "Transmission Security", description: "Implement technical security measures to guard against unauthorized access during transmission", priority: "P1" },
  { id: "164.312(e)(2)(i)", family: "Technical Safeguards", title: "Integrity Controls", description: "Implement security measures to ensure transmitted ePHI is not improperly modified", priority: "P1" },
  { id: "164.312(e)(2)(ii)", family: "Technical Safeguards", title: "Encryption", description: "Implement mechanism to encrypt ePHI whenever deemed appropriate", priority: "P1" },
  { id: "164.316(a)", family: "Documentation", title: "Policies and Procedures", description: "Implement reasonable and appropriate policies and procedures", priority: "P1" },
  { id: "164.316(b)(1)", family: "Documentation", title: "Documentation", description: "Maintain written policies and procedures and written records of required actions", priority: "P1" },
  { id: "164.316(b)(2)(i)", family: "Documentation", title: "Retention", description: "Retain documentation for six years from the date of its creation", priority: "P1" },
];

export const COMPLIANCE_FRAMEWORKS: Record<string, ComplianceFramework> = {
  "nist-800-53": {
    id: "nist-800-53",
    name: "NIST 800-53",
    version: "Rev. 5",
    description: "Security and Privacy Controls for Information Systems and Organizations",
    controls: NIST_800_53_CONTROLS,
  },
  "pci-dss": {
    id: "pci-dss",
    name: "PCI DSS",
    version: "4.0",
    description: "Payment Card Industry Data Security Standard",
    controls: PCI_DSS_REQUIREMENTS,
  },
  "soc2": {
    id: "soc2",
    name: "SOC 2",
    version: "2017",
    description: "Service Organization Control 2 Trust Services Criteria",
    controls: SOC2_CRITERIA,
  },
  "hipaa": {
    id: "hipaa",
    name: "HIPAA",
    version: "2023",
    description: "Health Insurance Portability and Accountability Act Security Rule",
    controls: HIPAA_CONTROLS,
  },
};

export const VULNERABILITY_TO_CONTROL_MAPPINGS: Record<string, Record<string, string[]>> = {
  "nist-800-53": {
    "SQL Injection": ["SI-10", "SA-11", "SC-8"],
    "Cross-Site Scripting": ["SI-10", "SA-11", "SC-8"],
    "Authentication Bypass": ["IA-2", "IA-5", "AC-7"],
    "Privilege Escalation": ["AC-6", "AC-5", "AC-3"],
    "Information Disclosure": ["SC-8", "SC-13", "AC-4"],
    "Remote Code Execution": ["SI-3", "CM-7", "SA-11"],
    "Command Injection": ["SI-10", "SA-11", "CM-7"],
    "Path Traversal": ["AC-3", "SI-10", "CM-7"],
    "Weak Cryptography": ["SC-13", "SC-8", "IA-5"],
    "Missing Authentication": ["IA-2", "AC-3", "AC-17"],
    "Insecure Configuration": ["CM-2", "CM-6", "CM-7"],
    "Unpatched Software": ["SI-2", "RA-5", "CM-7"],
    "Public Cloud Storage": ["SC-8", "AC-3", "AC-4"],
    "Overprivileged IAM": ["AC-6", "AC-5", "AC-2"],
    "Hardcoded Credentials": ["IA-5", "SC-8", "CM-6"],
    "Network Exposure": ["SC-7", "AC-17", "CM-7"],
  },
  "pci-dss": {
    "SQL Injection": ["6.3", "6.4", "11.3"],
    "Cross-Site Scripting": ["6.3", "6.4", "11.3"],
    "Authentication Bypass": ["8.1", "8.2", "8.3"],
    "Privilege Escalation": ["7.1", "7.2", "8.1"],
    "Information Disclosure": ["3.4", "4.1", "10.1"],
    "Remote Code Execution": ["5.1", "5.2", "6.2"],
    "Command Injection": ["6.3", "6.4", "11.3"],
    "Path Traversal": ["6.3", "7.1", "2.2"],
    "Weak Cryptography": ["3.5", "4.1", "8.2"],
    "Missing Authentication": ["8.1", "8.2", "8.3"],
    "Insecure Configuration": ["2.1", "2.2", "6.4"],
    "Unpatched Software": ["6.1", "6.2", "11.2"],
    "Public Cloud Storage": ["3.1", "3.4", "7.1"],
    "Overprivileged IAM": ["7.1", "7.2", "8.1"],
    "Hardcoded Credentials": ["8.2", "3.5", "2.1"],
    "Network Exposure": ["1.1", "1.2", "11.2"],
  },
  "soc2": {
    "SQL Injection": ["CC5.1", "CC5.2", "CC6.6"],
    "Cross-Site Scripting": ["CC5.1", "CC5.2", "CC6.6"],
    "Authentication Bypass": ["CC6.1", "CC6.2", "CC6.3"],
    "Privilege Escalation": ["CC6.1", "CC6.3", "CC5.1"],
    "Information Disclosure": ["C1.1", "CC6.7", "CC5.1"],
    "Remote Code Execution": ["CC6.6", "CC7.1", "CC5.2"],
    "Command Injection": ["CC5.1", "CC5.2", "CC6.6"],
    "Path Traversal": ["CC6.1", "CC5.1", "CC6.6"],
    "Weak Cryptography": ["CC6.7", "CC6.1", "C1.1"],
    "Missing Authentication": ["CC6.1", "CC6.2", "CC6.6"],
    "Insecure Configuration": ["CC5.2", "CC5.3", "CC8.1"],
    "Unpatched Software": ["CC7.1", "CC8.1", "CC5.2"],
    "Public Cloud Storage": ["C1.1", "CC6.1", "CC6.7"],
    "Overprivileged IAM": ["CC6.1", "CC6.3", "CC5.1"],
    "Hardcoded Credentials": ["CC6.1", "C1.1", "CC5.2"],
    "Network Exposure": ["CC6.6", "CC7.1", "CC7.2"],
  },
  "hipaa": {
    "SQL Injection": ["164.312(a)(1)", "164.312(c)(1)", "164.308(a)(1)"],
    "Cross-Site Scripting": ["164.312(a)(1)", "164.312(c)(1)", "164.308(a)(1)"],
    "Authentication Bypass": ["164.312(d)", "164.312(a)(2)(i)", "164.308(a)(4)"],
    "Privilege Escalation": ["164.312(a)(1)", "164.308(a)(4)", "164.308(a)(3)"],
    "Information Disclosure": ["164.312(e)(1)", "164.312(a)(2)(iv)", "164.312(c)(1)"],
    "Remote Code Execution": ["164.308(a)(1)", "164.312(a)(1)", "164.312(c)(1)"],
    "Command Injection": ["164.312(a)(1)", "164.312(c)(1)", "164.308(a)(1)"],
    "Path Traversal": ["164.312(a)(1)", "164.312(c)(1)", "164.308(a)(4)"],
    "Weak Cryptography": ["164.312(a)(2)(iv)", "164.312(e)(2)(ii)", "164.312(e)(1)"],
    "Missing Authentication": ["164.312(d)", "164.312(a)(1)", "164.308(a)(4)"],
    "Insecure Configuration": ["164.308(a)(1)", "164.316(a)", "164.308(a)(8)"],
    "Unpatched Software": ["164.308(a)(1)", "164.308(a)(8)", "164.312(a)(1)"],
    "Public Cloud Storage": ["164.312(e)(1)", "164.308(a)(4)", "164.312(a)(1)"],
    "Overprivileged IAM": ["164.308(a)(4)", "164.308(a)(3)", "164.312(a)(1)"],
    "Hardcoded Credentials": ["164.312(a)(2)(iv)", "164.312(d)", "164.308(a)(5)"],
    "Network Exposure": ["164.312(e)(1)", "164.308(a)(1)", "164.310(a)(1)"],
  },
};
