#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# OdinForge Server Setup Script
# Run on a fresh Ubuntu 22.04/24.04 VPS (DigitalOcean, Hetzner, etc.)
# Usage: sudo bash server-setup.sh
# =============================================================================

APP_DIR="/opt/odinforge"

echo "=== OdinForge Server Setup ==="
echo ""

# --- 1. Install Docker ---
if ! command -v docker &>/dev/null; then
    echo "[1/5] Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable docker
    echo "[1/5] Docker installed."
else
    echo "[1/5] Docker already installed, skipping."
fi

# --- 2. Create app directory ---
echo "[2/5] Creating $APP_DIR..."
mkdir -p "$APP_DIR"

# --- 3. Generate secrets ---
echo "[3/5] Generating secrets..."
PG_PW=$(openssl rand -hex 24)
SESSION_SEC=$(openssl rand -hex 32)
JWT_SEC=$(openssl rand -hex 32)
MINIO_PW=$(openssl rand -hex 24)
AGENT_TOK=$(openssl rand -hex 32)
CLOUD_KEY=$(openssl rand -hex 32)

# --- 4. Create .env file ---
if [ ! -f "$APP_DIR/.env" ]; then
    echo "[4/5] Creating .env file..."
    cat > "$APP_DIR/.env" <<ENVEOF
# Generated by server-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- EDIT THESE ---
DOMAIN=localhost
SERVER_URL=https://localhost
OPENAI_API_KEY=

# --- Auto-generated secrets (do not share) ---
POSTGRES_PASSWORD=$PG_PW
DATABASE_URL=postgresql://odinforge:${PG_PW}@postgres:5432/odinforge
REDIS_URL=redis://redis:6379
SESSION_SECRET=$SESSION_SEC
JWT_SECRET=$JWT_SEC

# MinIO / S3
MINIO_ROOT_USER=odinforge
MINIO_ROOT_PASSWORD=$MINIO_PW
STORAGE_ENDPOINT=http://minio:9000
STORAGE_BUCKET_NAME=odinforge
STORAGE_ACCESS_KEY_ID=odinforge
STORAGE_SECRET_ACCESS_KEY=$MINIO_PW
STORAGE_REGION=us-east-1
STORAGE_FORCE_PATH_STYLE=true

# Agent
AGENT_REGISTRATION_TOKEN=$AGENT_TOK
CLOUD_CREDENTIALS_KEY=$CLOUD_KEY
ENVEOF
    echo "[4/5] .env created at $APP_DIR/.env"
else
    echo "[4/5] .env already exists, skipping."
fi

# --- 5. Firewall ---
echo "[5/5] Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw allow 22/tcp
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw --force enable
    echo "[5/5] Firewall configured (SSH, HTTP, HTTPS)."
else
    echo "[5/5] ufw not found, skipping firewall."
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Point your domain A record to this server IP: $(curl -s ifconfig.me)"
echo "  2. Edit $APP_DIR/.env  -- set DOMAIN, SERVER_URL, OPENAI_API_KEY"
echo "  3. Copy docker-compose.prod.yml and Caddyfile to $APP_DIR/"
echo "  4. cd $APP_DIR && docker compose -f docker-compose.prod.yml up -d"
echo ""
